"""empty message

Revision ID: 11ef080dfd67
Revises: 3b30ed5a6b7b
Create Date: 2017-08-10 16:17:26.477162

"""

# revision identifiers, used by Alembic.
revision = '11ef080dfd67'
down_revision = '3b30ed5a6b7b'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_sellout_branchid_productid_selloutdate', 'sellout', ['branchid', 'productid', 'sellout_date'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_sellout_branchid_productid_selloutdate', table_name='sellout')
    ### end Alembic commands ###
