"""empty message

Revision ID: 17c3e68945fa
Revises: 41b556896c74
Create Date: 2017-07-13 00:01:30.491741

"""

# revision identifiers, used by Alembic.
revision = '17c3e68945fa'
down_revision = '41b556896c74'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute("""CREATE OR REPLACE FUNCTION BatchIndex(sn TEXT, tn TEXT, cn TEXT) RETURNS void AS $$
        DECLARE i_exists INTEGER;
        DECLARE idxname TEXT;
        BEGIN
          idxname := 'idx_' || tn || '_' || cn;
          select into i_exists count(*) from pg_class where relname = idxname;

          IF i_exists = 0 THEN
            EXECUTE 'CREATE INDEX ' ||idxname || ' ON '
              || sn || '.' || tn
              || ' USING GIST(' || cn || ')';
          END IF;
        END;
        $$ LANGUAGE plpgsql""")
    op.execute('SELECT BatchIndex(f_table_schema, f_table_name, f_geometry_column) FROM geometry_columns')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('DROP FUNCTION IF EXISTS BatchIndex(sn TEXT, tn TEXT, cn TEXT)')
    ### end Alembic commands ###
