"""empty message

Revision ID: 1a5e8a22b1ff
Revises: 27c290d7d797
Create Date: 2017-08-16 15:13:02.142582

"""

# revision identifiers, used by Alembic.
revision = '1a5e8a22b1ff'
down_revision = '27c290d7d797'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_boundary_typeid', 'boundary', ['typeid'])
    op.create_index('idx_boundary_parentid', 'boundary', ['parentid'])

    op.create_index('idx_branch_operation_started_date', 'branch', ['operation_started_date'])

    op.create_index('idx_sellout_sellout_date_productid_branchid', 'sellout', ['sellout_date', 'productid', 'branchid'],
                    unique=True)

    op.create_index('idx_territory_code', 'territory', ['code'], unique=True)

    op.create_index('idx_user_territory_userid', 'user_territory', ['userid'])
    op.create_index('idx_user_territory_territoryid', 'user_territory', ['territoryid'])

    op.create_index('idx_transaction_status', 'transaction', ['status'])
    op.create_index('idx_transaction_date', 'transaction', ['transaction_date'])
    op.create_index('idx_transaction_userid', 'transaction', ['userid'])
    op.create_index('idx_transaction_merchantid', 'transaction', ['merchantid'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_boundary_typeid', table_name='boundary')
    op.drop_index('idx_boundary_parentid', table_name='boundary')

    op.drop_index('idx_branch_operation_started_date', table_name='branch')

    op.drop_index('idx_sellout_sellout_date_productid_branchid', table_name='sellout')

    op.drop_index('idx_territory_code', table_name='territory')
    op.drop_index('idx_user_territory_userid', table_name='user_territory')
    op.drop_index('idx_user_territory_territoryid', table_name='user_territory')

    op.drop_index('idx_transaction_status', table_name='transaction')
    op.drop_index('idx_transaction_date', table_name='transaction')
    op.drop_index('idx_transaction_userid', table_name='transaction')
    op.drop_index('idx_transaction_merchantid', table_name='transaction')
    ### end Alembic commands ###
