"""empty message

Revision ID: 1d8b87a8cc4
Revises: 4e261c29d4f5
Create Date: 2017-08-09 18:52:27.955421

"""

# revision identifiers, used by Alembic.
revision = '1d8b87a8cc4'
down_revision = '4e261c29d4f5'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_branch_name_address', 'branch', ['name', 'address'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_branch_name_address', table_name='branch')
    ### end Alembic commands ###
