"""empty message

Revision ID: 1f1007d5da34
Revises: 21532f8c81df
Create Date: 2017-07-07 13:34:59.447121

"""

# revision identifiers, used by Alembic.
revision = '1f1007d5da34'
down_revision = '21532f8c81df'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branch', 'latlng',
               existing_type=geoalchemy2.types.Geometry(geometry_type=u'POINT'),
               nullable=True)
    op.alter_column('branch', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('branch', 'status',
               existing_type=sa.VARCHAR(length=10),
               nullable=False)
    op.alter_column('branch', 'latlng',
               existing_type=geoalchemy2.types.Geometry(geometry_type=u'POINT'),
               nullable=False)
    ### end Alembic commands ###
