"""empty message

Revision ID: 1f2ae6352873
Revises: 2410ac27f0f2
Create Date: 2017-07-21 14:28:12.782743

"""

# revision identifiers, used by Alembic.
revision = '1f2ae6352873'
down_revision = '2410ac27f0f2'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('status', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'status')
    ### end Alembic commands ###
