"""empty message

Revision ID: 21532f8c81df
Revises: 3ddcd0bf5dcf
Create Date: 2017-07-07 13:20:04.063996

"""

# revision identifiers, used by Alembic.
revision = '21532f8c81df'
down_revision = '3ddcd0bf5dcf'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boundary', sa.Column('geometry', geoalchemy2.types.Geometry(), nullable=True))
    op.drop_index('idx_boundary_geom', table_name='boundary')
    op.drop_column('boundary', 'geom')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boundary', sa.Column('geom', geoalchemy2.types.Geometry(), autoincrement=False, nullable=True))
    op.create_index('idx_boundary_geom', 'boundary', ['geom'], unique=False)
    op.drop_column('boundary', 'geometry')
    ### end Alembic commands ###
