"""empty message

Revision ID: 217ce1046981
Revises: 1f2ae6352873
Create Date: 2017-07-27 14:50:18.149137

"""

# revision identifiers, used by Alembic.
revision = '217ce1046981'
down_revision = '1f2ae6352873'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('transaction', sa.Column('travel_time_difference', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('travel_distance_in_km', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('next_average_travel_time_in_minutes', sa.Float(), nullable=True))
    op.add_column('transaction', sa.Column('next_travel_distance_in_km', sa.Float(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('transaction', 'travel_time_difference')
    op.drop_column('transaction', 'travel_distance_in_km')
    op.drop_column('transaction', 'next_average_travel_time_in_minutes')
    op.drop_column('transaction', 'next_travel_distance_in_km')
    ### end Alembic commands ###
