"""empty message

Revision ID: 23172f77f714
Revises: 1a5e8a22b1ff
Create Date: 2017-08-17 17:39:01.902949

"""

# revision identifiers, used by Alembic.
revision = '23172f77f714'
down_revision = '1a5e8a22b1ff'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_product_name_brand_material_code', 'product', ['name', 'brand', 'material_code'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_product_name_brand_material_code', table_name='product')
    ### end Alembic commands ###
