"""empty message

Revision ID: 2410ac27f0f2
Revises: 5610261dca52
Create Date: 2017-07-21 01:43:50.065624

"""

# revision identifiers, used by Alembic.
revision = '2410ac27f0f2'
down_revision = '5610261dca52'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branch_product', 'unit_of_measure')
    op.add_column('product', sa.Column('unit_of_measure', sa.String(length=50), server_default='PCS', nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'unit_of_measure')
    op.add_column('branch_product', sa.Column('unit_of_measure', sa.VARCHAR(length=50), autoincrement=False, nullable=True))
    ### end Alembic commands ###
