"""empty message

Revision ID: 25825326551b
Revises: 3848a02af6a2
Create Date: 2017-07-08 16:05:39.301094

"""

# revision identifiers, used by Alembic.
revision = '25825326551b'
down_revision = '3848a02af6a2'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE user_territory ALTER COLUMN date_assigned TYPE DATE')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.execute('ALTER TABLE user_territory ALTER COLUMN date_assigned TYPE DATETIME')
    ### end Alembic commands ###
