"""empty message

Revision ID: 27c290d7d797
Revises: 11ef080dfd67
Create Date: 2017-08-16 15:06:58.735747

"""

# revision identifiers, used by Alembic.
revision = '27c290d7d797'
down_revision = '11ef080dfd67'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('branch', sa.Column('branch_code', sa.String(length=30), nullable=True, index=True, unique=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branch', 'branch_code')
    ### end Alembic commands ###
