"""empty message

Revision ID: 2ff2b8ee8d86
Revises: 17c3e68945fa
Create Date: 2017-07-13 07:43:42.309426

"""

# revision identifiers, used by Alembic.
revision = '2ff2b8ee8d86'
down_revision = '17c3e68945fa'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'merchantid',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('transaction', 'merchantid',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
