"""empty message

Revision ID: 338b86e3337a
Revises: 552aec37026d
Create Date: 2017-07-08 12:08:59.167414

"""

# revision identifiers, used by Alembic.
revision = '338b86e3337a'
down_revision = '552aec37026d'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(u'boundary_parentid_fkey', 'boundary', type_='foreignkey')
    op.create_foreign_key(None, 'boundary', 'boundary', ['parentid'], ['id'])
    op.add_column('branch',
                  sa.Column('operation_started_date', sa.DateTime(), server_default=sa.func.current_timestamp(),
                            nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('branch', 'operation_started_date')
    op.drop_constraint(None, 'boundary', type_='foreignkey')
    op.create_foreign_key(u'boundary_parentid_fkey', 'boundary', 'boundary', ['parentid'], ['id'], ondelete=u'CASCADE')
    ### end Alembic commands ###
