"""empty message

Revision ID: 376786960ba6
Revises: 55540bae47a
Create Date: 2017-07-07 02:06:19.332578

"""

# revision identifiers, used by Alembic.
revision = '376786960ba6'
down_revision = '55540bae47a'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('firstname', sa.String(length=200), nullable=True))
    op.add_column('user', sa.Column('lastname', sa.String(length=200), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'lastname')
    op.drop_column('user', 'firstname')
    ### end Alembic commands ###
