"""empty message

Revision ID: 3b30ed5a6b7b
Revises: 1d8b87a8cc4
Create Date: 2017-08-10 16:02:17.892175

"""

# revision identifiers, used by Alembic.
revision = '3b30ed5a6b7b'
down_revision = '1d8b87a8cc4'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sellout',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date_created', sa.DateTime(), nullable=True),
    sa.Column('date_modified', sa.DateTime(), nullable=True),
    sa.Column('branchid', sa.Integer(), nullable=False),
    sa.Column('productid', sa.Integer(), nullable=False),
    sa.Column('sellout_date', sa.Date(), nullable=False),
    sa.Column('grossup_amount', sa.Numeric(), nullable=True),
    sa.ForeignKeyConstraint(['branchid'], ['branch.id'], ),
    sa.ForeignKeyConstraint(['productid'], ['product.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('product', sa.Column('brand', sa.String(length=200), nullable=True))
    op.add_column('product', sa.Column('material_code', sa.String(length=20), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('product', 'material_code')
    op.drop_column('product', 'brand')
    op.drop_table('sellout')
    ### end Alembic commands ###
