"""empty message

Revision ID: 3ddcd0bf5dcf
Revises: 376786960ba6
Create Date: 2017-07-07 02:21:12.175552

"""

# revision identifiers, used by Alembic.
revision = '3ddcd0bf5dcf'
down_revision = '376786960ba6'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('roleid', sa.Integer(), nullable=True))
    op.drop_constraint(u'user_role_id_fkey', 'user', type_='foreignkey')
    op.create_foreign_key(None, 'user', 'role', ['roleid'], ['id'])
    op.drop_column('user', 'role_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('role_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'user', type_='foreignkey')
    op.create_foreign_key(u'user_role_id_fkey', 'user', 'role', ['role_id'], ['id'])
    op.drop_column('user', 'roleid')
    ### end Alembic commands ###
