"""empty message

Revision ID: 41b556896c74
Revises: 13de023be759
Create Date: 2017-07-12 18:29:37.352516

"""

# revision identifiers, used by Alembic.
revision = '41b556896c74'
down_revision = '13de023be759'

from alembic import op
import sqlalchemy as sa
import geoalchemy2

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('boundary', sa.Column('has_data', sa.Boolean, server_default=sa.false()))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('boundary', 'has_data')
    ### end Alembic commands ###
