"""empty message

Revision ID: 552aec37026d
Revises: 1f1007d5da34
Create Date: 2017-07-07 15:58:23.713707

"""

# revision identifiers, used by Alembic.
revision = '552aec37026d'
down_revision = '1f1007d5da34'

from alembic import op
import sqlalchemy as sa
import geoalchemy2


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boundary', 'parentid',
               existing_type=sa.INTEGER(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('boundary', 'parentid',
               existing_type=sa.INTEGER(),
               nullable=False)
    ### end Alembic commands ###
